notifications:
  recipients:
    - groonga-commit@lists.sourceforge.jp
rvm:
  - 2.1
  - 2.2
  - 2.3.0
before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - sudo apt-get -qq -y install groonga-tokenizer-mecab
  - gem update bundler
install:
  - bundle install --jobs=3 --retry=3
  - |
    for test_app in test/apps/*
    do
      (cd ${test_app} && bundle install --jobs=3 --retry=3)
    done
script:
  - test/unit/run-test.rb
  - |
    for test_app in test/apps/*
    do
      (cd ${test_app} && bundle exec rake)
    done
