notifications:
  recipients:
    - groonga-commit@lists.sourceforge.jp
rvm:
  - 2.1
  - 2.2
  - 2.3.3
services:
  - mongodb
before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - sudo apt-get -qq -y install groonga-bin groonga-tokenizer-mecab
  - gem update bundler
  - git clone --depth 1 https://github.com/ranguba/groonga-client.git ../groonga-client
install:
  - bundle install --jobs=3 --retry=3
  - |
    for test_app in ${PWD}/test/apps/*
    do
      if echo ${test_app} | grep -q rails5; then
        if ruby --version | grep -q 'ruby 2.1'; then
          continue
        fi
      fi
      (cd ${test_app} && \
       rm Gemfile.lock && \
       BUNDLE_GEMFILE=${test_app}/Gemfile bundle install --jobs=3 --retry=3)
    done
script:
#  - bundle exec ruby test/unit/run-test.rb
  - |
    for test_app in ${PWD}/test/apps/*
    do
      if echo ${test_app} | grep -q rails5; then
        if ruby --version | grep -q 'ruby 2.1'; then
          continue
        fi
      fi
      (cd ${test_app} && \
       BUNDLE_GEMFILE=${test_app}/Gemfile bundle exec rake)
    done
